name: Lint

on:
  pull_request:
    branches:
      - master
      - main
      - cardillo-core

jobs: 
  lint:
    # runs-on: [self-hosted, linux]
    runs-on: [ubuntu-latest] 
    steps:
      - uses: actions/checkout@v2
      - run: |
          pip install black
          python -m black . --check --diff